### ISSUE TITLE
Upgrade kubernetes-server-mock to 5.12.2 in operator-framework-spring-boot-starter-parent to be compatible with operator-framework-core

### ISSUE THREAD

**Issue by zhannicholas** [java-operator-sdk/operator-framework-spring-boot-starter#20]
Currently, the kubernetes-server-mock in test scope in operator-framework-spring-boot-starter-parent is 5.11.2, but the latest operator-framework-core has the kubernetes-server-mock with version 5.12.2. The two versions are incompatible because of their transitive dependency on kubernetes-module-core.

In operator-framework-core 3.0.2, `io.javaoperatorsdk.operator.ReconcilerUtils#isFinalizerValid` called `HashMetadata.validateFinalizer(finalizer)`, but this method is not available for kubernetes-server-mock 5.11.2 (in fact, it's dependency kubernetes-model-core 5.11.2 doesn't have this method, but version 5.12.2 has this method).

I have a test dependency for Reconcilers:
```xml
<dependency>
          <groupId>io.javaoperatorsdk</groupId>
          <artifactId>operator-framework-spring-boot-starter-test</artifactId>
          <version>3.0.0</version>
          <scope>test</scope>
</dependency>
```
But the test will failed to compile because:
```txt
Exception in thread "OkHttp Dispatcher" java.lang.NoSuchMethodError: io.fabric8.kubernetes.api.model.HasMetadata.validateFinalizer(Ljava/lang/String;)Z
	at io.javaoperatorsdk.operator.ReconcilerUtils.isFinalizerValid(ReconcilerUtils.java:30)
	at io.javaoperatorsdk.operator.api.config.AnnotationControllerConfiguration.getFinalizerName(AnnotationControllerConfiguration.java:59)
	at io.javaoperatorsdk.operator.springboot.starter.OperatorAutoConfiguration$ConfigurationWrapper.getFinalizerName(OperatorAutoConfiguration.java:167)
	at io.javaoperatorsdk.operator.processing.event.source.controller.ResourceEventFilters.lambda$static$0(ResourceEventFilters.java:13)
	at io.javaoperatorsdk.operator.processing.event.source.controller.ResourceEventFilters.lambda$or$6(ResourceEventFilters.java:157)
	at io.javaoperatorsdk.operator.processing.event.source.controller.ResourceEventFilter.lambda$and$0(ResourceEventFilter.java:39)
	at io.javaoperatorsdk.operator.processing.event.source.controller.ControllerResourceEventSource.eventReceived(ControllerResourceEventSource.java:63)
	at io.javaoperatorsdk.operator.processing.event.source.controller.ControllerResourceEventSource.onAdd(ControllerResourceEventSource.java:78)
	at io.javaoperatorsdk.operator.processing.event.source.controller.ControllerResourceEventSource.onAdd(ControllerResourceEventSource.java:23)
	at io.fabric8.kubernetes.client.informers.cache.ProcessorListener$AddNotification.handle(ProcessorListener.java:96)
	at io.fabric8.kubernetes.client.informers.cache.ProcessorListener.add(ProcessorListener.java:47)
	at io.fabric8.kubernetes.client.informers.cache.SharedProcessor.lambda$distribute$0(SharedProcessor.java:79)
```

I have to manually add kubernetes-server-mock 5.12.2 to override the default version 5.11.2 provided by the starter-test to make it compile successfully.
```xml
<dependency>
            <groupId>io.fabric8</groupId>
            <artifactId>kubernetes-server-mock</artifactId>
            <version>5.12.2</version>
            <scope>test</scope>
</dependency>
```

I'm very happy to help fix this if the team agree me to do this.

**Comment by csviri** [comment]
please do @zhannicholas, thank you!
